/**
 * Generates src/data/sidoRegions.ts — the 시군 / 시군구 name list per sido.
 *
 * These lists are the only unique on-page text the /maps/{level}/{sido}/ pages
 * carry; without them all 16 filtered pages are the same PDF-card template with
 * a swapped heading, and Google collapses them onto the nationwide page. Baked
 * in at build time rather than fetched: the page otherwise needs none of the
 * ~900KB TopoJSON, and pre-rendered HTML must contain the names to be worth it.
 *
 * Run: node scripts/genSidoRegions.mjs  (after any public/data change)
 */

import { readFile, writeFile, mkdir } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const SRC = join(ROOT, 'public/data/korea-sigungu.json');
const OUT = join(ROOT, 'src/data/sidoRegions.ts');

// Mirrors SIDO_SLUG in regionUtils.ts — 세종(29) has no filtered page.
const SIDO_CODES = [
  '11', '21', '22', '23', '24', '25', '26',
  '31', '32', '33', '34', '35', '36', '37', '38', '39',
];
const METRO = new Set(['11', '21', '22', '23', '24', '25', '26']);

const topo = JSON.parse(await readFile(SRC, 'utf8'));
const geometries = topo.objects[Object.keys(topo.objects)[0]].geometries;

const entries = geometries.map((g) => ({
  code: g.properties.SIG_CD,
  name: g.properties.SIG_KOR_NM,
}));

/** Same grouping rule as buildSigunData: "수원시 장안구" → 수원시, code → first 4 digits. */
function toSigun(list) {
  const out = [];
  const seen = new Set();
  for (const { code, name } of list) {
    const compound = name.includes(' ');
    const nameKo = compound ? name.split(' ')[0] : name;
    if (seen.has(nameKo)) continue;
    seen.add(nameKo);
    out.push({ code: compound ? code.substring(0, 4) : code, nameKo });
  }
  return out;
}

const data = {};
for (const sido of SIDO_CODES) {
  const list = entries.filter((e) => e.code.startsWith(sido));
  data[sido] = {
    sigungu: list.map(({ code, name }) => ({ code, nameKo: name })),
    // 광역시는 시군 뷰가 없다 (자치구가 곧 최상위 분할).
    sigun: METRO.has(sido) ? [] : toSigun(list),
  };
}

const body = Object.entries(data)
  .map(([sido, { sigun, sigungu }]) => {
    const fmt = (arr) =>
      arr.length === 0
        ? '[]'
        : `[\n${arr.map((r) => `      { code: '${r.code}', nameKo: '${r.nameKo}' },`).join('\n')}\n    ]`;
    return `  '${sido}': {\n    sigun: ${fmt(sigun)},\n    sigungu: ${fmt(sigungu)},\n  },`;
  })
  .join('\n');

const out = `// GENERATED by scripts/genSidoRegions.mjs — do not edit by hand.
// Source: public/data/korea-sigungu.json (SGIS 2025)

export interface SidoRegionEntry {
  /** SIG_CD, or its first 4 digits for a merged compound city (수원시 etc). */
  code: string;
  nameKo: string;
}

export interface SidoRegionLists {
  /** 도 only — 광역시는 빈 배열. */
  sigun: SidoRegionEntry[];
  sigungu: SidoRegionEntry[];
}

export const SIDO_REGIONS: Record<string, SidoRegionLists> = {
${body}
};
`;

await mkdir(dirname(OUT), { recursive: true });
await writeFile(OUT, out, 'utf8');
console.log(
  `wrote ${OUT}\n` +
    SIDO_CODES.map((s) => `  ${s}: sigun ${data[s].sigun.length}, sigungu ${data[s].sigungu.length}`).join('\n'),
);
